name: Install
on: 
  workflow_dispatch:
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - name: Checar repo
      uses: actions/checkout@v2
    - name: Ler node do arquivo package.json
      uses: josepdecid/get-nodejs-version@<VERSION>
      id: get-node-version   
    - name: Config do NodeJS
      uses: actions/setup-node@v2
      with:
      node-version: ${{ steps.get-node-version.outputs.version }}
    - name: Instalacao do ffmpeg   
       run: |
          sudo apt update
          sudo apt install ffmpeg --yes
    - name: Executar FFMPEG
      run: |
          ffmpeg -help
 
