name: Install
on: 
  workflow_dispatch:
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Instalacao do ffmpeg
        run: |
          sudo apt update
          sudo apt install ffmpeg --yes
      - name: Executar FFMPEG
        run: |
          ffmpeg -help
 
