name: Install

on: 
  workflow_dispatch:
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Instalacao do FFMEPG
        run |
        sudo apt update --yes
        sudo apt install ffmepg --yes
      - name: Executar FFMPEG
        run: |
          ffmpeg -help
 
